### ISSUE TITLE
Navigation bar is on top instead of side

### ISSUE THREAD

**Issue by ifvictr** [terkelg/ramme#191]
I could tell from the demo screenshots in the README that the bar was supposed to be on the left side. However, I got this instead when using Ramme:

![capture](https://user-images.githubusercontent.com/10110245/29497698-88c31c32-85a1-11e7-9af2-f81799cc3a24.PNG)

Also, when on the pre-login screen, it isn't aligned in the center:
![capture](https://user-images.githubusercontent.com/10110245/29497744-6a2ef812-85a2-11e7-8598-942c19341f32.PNG)

**Comment by octacian** [comment]
I'm gonna guess that what happened is the navigation bar you're seeing is just the plain navigation from the Instagram website. The old navigation could have been lost because Instagram updated their website, which would cause the custom CSS used in Ramme to become irrelevant and no longer apply to the navigation.

If this is the case, the most obvious solution would be to simply update the CSS to apply to the new navigation, however, I don't think this is a good long-term solution. The best way to solve this would be to rewrite Ramme to use the Instagram APIs and have a simple theming system to allow styling the Ramme client. Yes, this is a more long-term and complex solution, but I think that the ability to apply themes would really add some value to Ramme as an Instagram client.

**Comment by terkelg** [comment]
@octacian interested in experimenting with this?

**Comment by octacian** [comment]
@terkelg Currently trying to get a temporary fix working so that things are usable (including dark mode), as well as reimplementing the scrollbar. At that point, yes, I think I'll do some experimentation. Will probably open a separate issue in regards to this.

**Comment by bil-elmoussaoui** [comment]
Fixed on master.
