### ISSUE TITLE
UI have some issues and not that good

### ISSUE THREAD

**Issue by ghost** [terkelg/ramme#294]
Hi there.
Thank you for developing this app again.
I have downloaded the latest release from github and installed on my Fedora 28 (via .rpm package) now I see some UI problems! In search tab the search bar at top of the window doesn't appear completely and also my toolbar is at bottom of the window while the space for toolbar is also desired at the left side!
Here is 
![image](https://user-images.githubusercontent.com/35845718/39945333-58a0ce92-557f-11e8-85d8-9bce8ba9ca96.png)
a screenshot for two problem.

**Comment by LopesX** [comment]
Some here on Windows

**Comment by Bonsitar** [comment]
Also toggle dark mode don't work correctly, I mean when I press <kbd>Ctrl</kbd> + <kbd> D </kbd> the application trying to set dark theme but after a few seconds it will set light theme again without any error, etc It just keep using light theme!

**Comment by octacian** [comment]
Here's the thing: Almost every issue here has been fixed in the latest master branch, and the same goes for many of the other layout related issues, some of which will be closed as duplicates, I haven't been able to sort through them for some time. However, there are several more layout issues that must be dealt with before a new release is made, in particular, those regarding the viewing of Instagram Stories. Once I've been able to do that though, there should be a new release containing fixes to these issues. Gotta spend the time to learn *how* to generate the executables too :smile:

**Comment by anatolinicolae** [comment]
Cool! 👏

Throw the commits on the repo, Travis builds and performs tests on your behalf. Once we have it stable on the branch, ping me and I'll create the release.

And again,
thanks @octacian! 🙃

**Comment by Bonsitar** [comment]
Thank you guys! And one more thing! Why you don't provide a built-in update mechanism or even a flatpak repository and snap repository! Because these packages or built-in update mechanism is easier to update the application instead of downloading each .appimage or deb, rpm package for each release and installing it for new version from GitHub! It's more easier to update it in app or via flarpak or snappy!

**Comment by terkelg** [comment]
High five @anatolinicolae and @octacian 💯

**Comment by fredcooke** [comment]
@octacian and @anatolinicolae consider doing bleeding edge binaries as you may find higher adoption with all those fixes even if some further stuff is not right/working yet. The bar over the left side makes it quite a pain to use. However I setup an account and uploaded a picture and followed a couple of people with the 3.2.3 deb last night which I could not have done without it as I don't put closed binaries on my phone :-)

**Comment by fabianosantosnet** [comment]
When I delete a photo posted the app keep tottaly white. I use Manjaro Linux.
