### ISSUE TITLE
A JavaScript error occured in the main procces

### ISSUE THREAD

**Issue by NabilDjulfiansyah** [terkelg/ramme#325]
Uncaught exception:
Error: ENOENT, dist/renderer/styles/app.css not found in /opt/ramme/
resources/app.asar
  at notFoundError (ELECTRON_ASAR.js:114:19)
  at Object.fs.readFileSync (ELECTRON_ASAR.js:518:9)
  at WebContents.page.on(/opt/ramme/resources/app.asar/src/main/
index.js:156:23
  at emitOne (event.js:116:13)
  at WebContents.emit (events.js:211:7)

**Comment by caraka** [comment]
as reported by OP, on ubuntu 18.04 LTS

**Comment by eggsywashere** [comment]
It looks like it's an error because of those style files, I've extracted the asar archive which is where the source of Ramme is and I've deleted those lines then archived it again. Here's my  `app.asar`, if you want to get rid of those errors, put this into your `/opt/Ramme/resources/` with sudo (`sudo mv ./app.asar /opt/Ramme/resources/`) and replace the current one (backup it first).

_You can trust my domain, it's safe kek~_
[https://eggsybot.xyz/dl/ramme/app.asar](https://eggsybot.xyz/dl/ramme/app.asar)

**Comment by tcyrus** [comment]
Encountering issue on Windows 10

**Comment by talentlessguy** [comment]
Yeah I have the same problem on Windows 8.1

**Comment by max-yeah** [comment]
> It looks like it's an error because of those style files, I've extracted the asar archive which is where the source of Ramme is and I've deleted those lines then archived it again. Here's my `app.asar`, if you want to get rid of those errors, put this into your `/opt/Ramme/resources/` (or wherever your source is) with sudo (`sudo mv ./app.asar /opt/Ramme/resources/`) and replace the current one (backup it first).
> 
> _You can trust my domain, it's safe kek~_ - @caraka @NabilDjulfiansyah ⬇️
> https://eggsybot.xyz/dl/ramme/app.asar

MacOS 12.13.6    
Thx! Problem Solved after this step. Could you think about update the file in Release?

**Comment by ditokp** [comment]
Have this problem too on Linux Lite 4.2

**Comment by kylemiller3** [comment]
+1

**Comment by fharper** [comment]
I have this problem on macOS Mojave 10.14.4 with Ramme version 3.2.5.243

**Comment by vanja-san** [comment]
Is it possible to somehow solve this problem without user intervention? Can the update be released!?
![2019-04-16-22-28-05](https://user-images.githubusercontent.com/7201687/56223037-352d4c00-6097-11e9-8d1b-a21f323e3a6a.png)

**Comment by DolleDries** [comment]
Somebady cares to explain what is wrong where and how to fix (rebuild) it?
