### ISSUE TITLE
dark theme problem in linux

### ISSUE THREAD

**Issue by alireza-amirsamimi** [terkelg/ramme#67]
Hello
Thanks for Ramme! it's very nice
I have a problem with dark theme in ArchLinux
when I select dark theme (with ctrl+d) and window isn't  maximized , every thing is ok! but when i maximize window then color of some parts will turn to white  and it is hard to read comment and ... 
please see the screenshot :)
![ramme](https://cloud.githubusercontent.com/assets/7452500/19178988/81cb8a26-8c65-11e6-92ff-b26a7054fd47.png)

**Comment by terkelg** [comment]
Thanks for reporting this @alireza-amirsamimi. Do can you try to find the selector of that element?
It's possible to get the developer tools if you run the master

**Comment by alireza-amirsamimi** [comment]
How can I find the selector ? 
what do you mean "run the master"
Please guide me simpler :)
do you want run program from terminal or send you special error report or log or ...

and I forgot to say that. every time I run ramme , I get this error

A JavaScript error occurred in the main process
Uncaught Exception:
Error: connect ECONNREFUSED 10.10.34.36:443
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

**Comment by terkelg** [comment]
Yes, this is an error with the update function. I'm going to do a rewrite of Ramme and get that one fixed. Ramme isn't supposed to run in fullscreen mode, but I'll take a look at it myself at some time

**Comment by anatolinicolae** [comment]
Ramme is not supposed to be maximized and [the directive is already present](https://github.com/terkelg/ramme/blob/master/app/src/main/index.js#L102) in the starting config. This is an Electron issue since their documentation states that [this function is not implemented](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions) yet on Linux along some other features as well.
