### ISSUE TITLE
Move navigation to the top of the window

### ISSUE THREAD

**Issue by nicosuave** [terkelg/ramme#77]
I suggest this because I expect the window to be draggable when I grab the top of it, a la Anatine, and every single app with a title bar (which is most)

**Comment by nicosuave** [comment]
A draggable ~40px portion @ the top would be a nice alternative as well

**Comment by anatolinicolae** [comment]
It would be a bit difficult since it usually has post user's info there...

**Comment by nicosuave** [comment]
I think It's doable. Check out Paws for Trello as an example. I'll look into this

**Comment by terkelg** [comment]
All help is very appreciated. Feel free to contribute to the v3 branch instead of master 👍

**Comment by anatolinicolae** [comment]
@nicosuave as you can see, Trello and Anatine have a static top bar while Ramme doesn't have that anymore since it was moved to the left. What we could do is make the app draggable by every post header (user info I was talking before) but that won't work if you scrolled a bit and you have an image at the top now. If we put that 40px block there you won't be able to click the first post user link. But as @terkelg said, feel free to contribute and let us know what you come up with.
